### ISSUE TITLE
[Ask] Discord Webhook Template

### ISSUE THREAD

**Issue by tarokeitaro** [jellyfin/jellyfin-plugin-webhook#117]
### How do I make the webhook look like this image?
![image](https://user-images.githubusercontent.com/42670754/168824878-dfc3b2ff-4d40-49e3-bd88-de89e3f1fb18.png)

I wrote this, but it didn't work.
```
{
  "content": "
  {{~#if_exist ItemType 'Episode'~}}{{{SeriesName}}} S{{{SeasonNumber00}}}E{{{EpisodeNumber00}}} has been added to Jellyfin Server | k-mediaserver - {{ItemType}}{{~/if_exist~}}
  {{~#if_exist ItemType 'Movie'~}}{{{Name}}} has been added to Jellyfin Server | k-mediaserver - {{ItemType}}{{~/if_exist~}}
  {{~#if_exist ItemType 'Audio'~}}{{{Name}}} has been added to Jellyfin Server | k-mediaserver - {{ItemType}}{{~/if_exist~}}
  ",
  "embeds": null,
  "attachments": []
}
```
Please help me! :)

**Comment by tarokeitaro** [comment]
it does not send anything to Discord

**Comment by tarokeitaro** [comment]
Sorry if I am not good at this. I have followed the documentation, but here I am asking if the code ```{{~#if_exist ItemType 'Episode'~}}``` is invalid?
When I write ```{{~#if_exist SeriesName~}}``` it runs. But that's not what Im looking for.

**Comment by crobibero** [comment]
`{{~#if_equals ItemType 'Episode'~}}`

**Comment by tarokeitaro** [comment]
Now the webhook sends notifications as per the items I uploaded. Greatly appreciate the assistance.
```
{
  "content": "
  {{~#if_equals ItemType 'Movie'~}}[Movie] {{{Name}}} has been added to Jellyfin Server | k-mediaserver{{~/if_equals~}}
  {{~#if_equals ItemType 'Episode'~}}[TV Series] {{{SeriesName}}} S{{{SeasonNumber00}}}E{{{EpisodeNumber00}}} has been added to Jellyfin Server | k-mediaserver{{~/if_equals~}}
  {{~#if_equals ItemType 'Audio'~}}[Music] {{{Name}}} has been added to Jellyfin Server | k-mediaserver{{~/if_equals~}}
  ",
  "embeds": null,
  "attachments": []
}
```

The output will be like this.
![image](https://user-images.githubusercontent.com/42670754/168976735-e57c60a5-2675-4afd-9bf7-f331cd6f4c38.png)
