### ISSUE TITLE
Telegram webhook help

### ISSUE THREAD

**Issue by itsboo07** [jellyfin/jellyfin-plugin-webhook#136]
Hi firstly thanks for this great project..
Im trying out simple webhook commands but not working....
Im trying to send a message to telegram bot when Playback start or stop
Under add generic destination. 
Web hook url is
`https://api.telegram.org/bot{api}/sendMessage`
And template is
`{
  "chat_id":"mychatid", 
  “text”: “jellyfin media Playback test”
}`
And notification type is Playback start and Playback stop
Even though I try to play video or pause or stop it.. I don't get any message to telegram.... What am i missing? 
What should be the webhook server url(may be that's where I'm doing mistake)? 
I access jellyfin http://192.168.0.160:8096(I run jellyfin server in windows 11)
![Screenshot_2022-10-04-02-23-05-855_com kiwibrowser browser](https://user-images.githubusercontent.com/87331871/193693241-c6cf01e0-5def-46f6-be25-a931376fe297.png)
In logs i get this error
`[2022-10-04 03:05:32.626 +05:30] [WRN] [29] Jellyfin.Plugin.Webhook.Destinations.Generic.GenericClient: Notification failed with response status code BadRequest: "{\"ok\":false,\"error_code\":400,\"description\":\"Bad Request: message text is empty\"}"`

when i tried this in browser, it works and sends msg to telegram
`https://api.telegram.org/bot{token}/sendMessage?chat_id={my_chat_id}&text=/test/}`
and this sends message as `/test/`
 
 also tested in nodered and it works their too
 
![image](https://user-images.githubusercontent.com/87331871/193701806-a56ba55b-1c13-4b2e-8024-ae744e0dc214.png)

**Comment by xiNeRoar** [comment]
I have the same issue...no idea what server URL and base URL mean. Cannot find any clear explanation in the documentation :(

**Comment by itsboo07** [comment]
> I have the same issue...no idea what server URL and base URL mean. Cannot find any clear explanation in the documentation :(

I got it working... If you need support let me know

**Comment by xiNeRoar** [comment]
> > I have the same issue...no idea what server URL and base URL mean. Cannot find any clear explanation in the documentation :(
> 
> I got it working... If you need support let me know

May i know how did you get it work? I still couldn't fogure out what should i fill in in thay blank

**Comment by hardwareadictos** [comment]
> > I have the same issue...no idea what server URL and base URL mean. Cannot find any clear explanation in the documentation :(
> 
> I got it working... If you need support let me know

Can you share the solution please?

**Comment by roolala** [comment]
Hi @itsboo07

Could you share your solution?

Thanks

**Comment by roolala** [comment]
As I didn't find many info here is what I did to have some telegram notification, but it only works for new movies and episodes.

- The "Server URL" field is the URL your jellyfin is accessible from. `https://domain.tld`
- Click "Add Generic destination"
- In the `Webhook URL` fill it with `https://api.telegram.org/bot<bot_token>/sendPhoto` and replace the `<bot_token>` with your bot token (cf. [medium article](https://medium.com/geekculture/generate-telegram-token-for-bot-api-d26faf9bf064))
- The template I'm currently using is:
```json
{"chat_id":"{{chatid}}",   
"photo":"{{ServerUrl}}/Items/{{ItemId}}/Images/Primary",
   {{#if_equals ItemType 'Season'}}
       "caption": "<b>{{ItemType}} Now Available</b>\n\n<b>{{{SeriesName}}} ({{Year}})</b>\n<b><em>{{{Name}}}</em></b>\n{{Overview}}\n\n<b>Runtime</b>\n{{RunTime}}\n\n<b>Status</b>\nAvailable"
   {{else}}
       {{#if_equals ItemType 'Episode'}}
           "caption": "<b>Episode Now Available</b>\n\n<b>{{{SeriesName}}} ({{Year}})</b>\n<b>S{{SeasonNumber00}}E{{EpisodeNumber00}}</b> - <b><em>{{{Name}}}</em></b>\n{{Overview}}\n\n<b>Runtime</b>\n{{RunTime}}\n\n<b>Status</b>\nAvailable"
    {{else}}
       "caption": "<b>{{ItemType}} Now Available</b>\n\n<b>{{{Name}}} ({{Year}})</b>\n{{Overview}}\n\n<b>Runtime</b>\n{{RunTime}}\n\n<b>Status</b>\nAvailable"
   {{/if_equals}}
{{/if_equals}},
"parse_mode": "html",
"disable_notification":"true","protect_content":"true"
}
```
- After clicking the "Add request header" button fill the key and value like described in the [README.md](https://github.com/jellyfin/jellyfin-plugin-webhook/blob/master/Jellyfin.Plugin.Webhook/Templates/README.md) in the templates directory
- Clicking one more time on "Add request header" to create the `chatid` key (which corresponds to the key in the previous template) and the chat ID of your telegram group as the value (cf. this [stackoverflow comment](https://stackoverflow.com/a/32572159) on how to get the chat ID group.

I hope it will help some one 😃
