### ISSUE TITLE
Sending non-ascii characters results in html escape

### ISSUE THREAD

**Issue by Coro365** [jellyfin/jellyfin-plugin-webhook#144]
Sending non-ascii characters results in **HTML Escape (decimal)** strings.
In jellyfin, it seems to be saved with **Unicode Escape (hex)**.
https://mottie.github.io/Unicode/index6.html

I don't know the details, but I think there is a problem with the decode.

https://github.com/jellyfin/jellyfin-plugin-webhook/blob/1bb78e36985a3bb6fdc97b07d9a30c0495b629e5/Jellyfin.Plugin.Webhook/Configuration/Web/config.js#L419
`String.fromCharCode()` may be available.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/fromCharCode

Thank you.  
## Environment
jellyfin: version 10.8.7  
jellyfin-plugin-webhook: version 11.0.0.0  
 
Template: `{{ SeriesName }} #{{ EpisodeNumber }} {{ Name }}`  
Expect: `「艦これ」いつかあの海で #2 海峡へ`  
Actual: `&#12300;&#33382;&#12371;&#12428;&#12301;&#12356;&#12388;&#12363;&#12354;&#12398;&#28023;&#12391; #2 &#28023;&#23777;&#12408;`  

Sent to ntfy with general destination settings.
https://ntfy.sh/

## Part of log
```
{
	"ServerId": "6db8b6fcd41b4e0da04b99b673d4ba89",
	"ServerName": "(...)",
	"ServerVersion": "10.8.7",
	"ServerUrl": "(...)",
	"NotificationType": "ItemAdded",
	"Timestamp": "2022-11-11T23:42:34.59708+09:00",
	"UtcTimestamp": "2022-11-11T14:42:34.597082Z",
        (...)
	"ItemId": "125ba264660259dbb88cc2e0942fe7f9",
	"ItemType": "Episode",
        (...)
	"SeriesName": "\u300C\u8266\u3053\u308C\u300D\u3044\u3064\u304B\u3042\u306E\u6D77\u3067",
	"SeasonNumber": 2,
        (...)
}
```

**Comment by hardwareadictos** [comment]
Same issue here with Spanish and special characters like accents ("´"):

Episode Now Available

NCIS: Los Ángeles (2009)
S02E01 - Tráfico humano
Un detective del Departamento de polic&#237;a de Los Angeles desaparece durante una peligrosa misi&#243;n secreta. El equipo deber&#225; ayudar a la polic&#237;a en este caso, aunque al nuevo jefe de investigaci&#243;n, Scarli, no se lo pondr&#225; nada f&#225;cil a Callen y a su equipo. Pero, adem&#225;s, esta la operaci&#243;n se complicar&#225; cuando descubren que est&#225; relacionado con el tr&#225;fico de personas, drogas y falsificaci&#243;n de dinero. Mientras Hetty y Nate son enviados a una misi&#243;n tan secreta, tan secreta que Nate tendr&#225; que trabajar sin tener detalles sobre la misma. Y Callen intentar&#225; recomponer su pasado e identificar al misterioso hombre que le observaba en el cementerio.

**Comment by Coro365** [comment]
Hello.
In C#, I was able to decode it properly using `HttpUtility.HtmlDecode()`.

```
using System;
using System.Web;
					
public class Program
{
	public static void Main()
	{
		// string base64EncodedData = "aGVsbG8sIHdvcmxkIQ==";   // natural
		string base64EncodedData = "JiMxMjMwMDsmIzMzMzgyOyYjMTIzNzE7JiMxMjQyODsmIzEyMzAxOyYjMTIzNTY7JiMxMjM4ODsmIzEyMzYzOyYjMTIzNTQ7JiMxMjM5ODsmIzI4MDIzOyYjMTIzOTE7ICMyICYjMjgwMjM7JiMyMzc3NzsmIzEyNDA4Ow==";   // Japanese
		// string base64EncodedData = "JiM3ODsmIzY3OyYjNzM7JiM4MzsmIzU4OyYjMzI7JiM3NjsmIzExMTsmIzExNTsmIzMyOyYjMTk1OyYjMTI5OyYjMTEwOyYjMTAzOyYjMTAxOyYjMTA4OyYjMTAxOyYjMTE1OyYjMzI7JiM0MDsmIzUwOyYjNDg7JiM0ODs=";   // Spanish
		// string base64EncodedData = "JiMxMDg4OyYjMTExMDsmIzEwODI7LiAmIzEwNTk7ICYjMTA5MDsmIzEwODY7JiMxMDc0OyYjMTA3MjsmIzEwODg7JiMxMDgwOyYjMTA4OTsmIzEwOTA7JiMxMDc0OyYjMTExMDsgJiMxMDg5OyYjMTA3NDsmIzEwODY7";   // Ukrainian
		
		var base64EncodedBytes = Convert.FromBase64String(base64EncodedData);
                string escapedString = System.Text.Encoding.UTF8.GetString(base64EncodedBytes);
		
		// string escapedString = "hello, world!";   // natural
		// string escapedString = "&#12300;&#33382;&#12371;&#12428;&#12301;&#12356;&#12388;&#12363;&#12354;&#12398;&#28023;&#12391; #2 &#28023;&#23777;&#12408;";   // Japanese
		// string escapedString = "&#78;&#67;&#73;&#83;&#58;&#32;&#76;&#111;&#115;&#32;&#195;&#129;&#110;&#103;&#101;&#108;&#101;&#115;&#32;&#40;&#50;&#48;&#48;";  // Spanish
		// string escapedString = "&#1088;&#1110;&#1082;. &#1059; &#1090;&#1086;&#1074;&#1072;&#1088;&#1080;&#1089;&#1090;&#1074;&#1110; &#1089;&#1074;&#1086;";    // Ukrainian 
		
		string naturalString = HttpUtility.HtmlDecode(escapedString);

		Console.WriteLine(naturalString);
	}
}
```
Adding it in this vicinity might work.
https://github.com/jellyfin/jellyfin-plugin-webhook/blob/a10d90e527a86a8f2268cedbdd09e87993153f94/Jellyfin.Plugin.Webhook/Helpers/HandlebarsFunctionHelpers.cs#L78

Thank you!

### Test environment
- run
  - https://dotnetfiddle.net/Dzb8qy
- test encode
  - https://www.hashemian.com/tools/html-url-encode-decode.php
  - https://dencode.com/

**Comment by Coro365** [comment]
As the comment below points out, using **Triple-Stash** solved the problem.
https://github.com/jellyfin/jellyfin-plugin-webhook/issues/148#issuecomment-1727931307

https://handlebarsjs.com/guide/#html-escaping

old template: `{{ SeriesName }} #{{ EpisodeNumber }} {{ Name }}` 
new template: `{{{ SeriesName }}} #{{{{ EpisodeNumber }}} {{{ Name }}}`

Thank you everyone!
