### ISSUE TITLE
Item Added notification sent before content metadata is added

### ISSUE THREAD

**Issue by seanmcbroom** [jellyfin/jellyfin-plugin-webhook#160]
The Item Added notification will sometimes fire before content metadata is added, causing things like the overview or poster image to not be available.

Example:
![image](https://user-images.githubusercontent.com/57121175/215410959-62972edb-322d-4548-9f72-d42a0eb943c3.png)

**Comment by crobibero** [comment]
The plugin waits a good amount of time to ensure that metadata is populated before sending the item added notification. Maybe we need to increase the delay

**Comment by seanmcbroom** [comment]
It works a good amount of the time. Just a few times where it doesn't is annoying.
