### ISSUE TITLE
Configure notification

### ISSUE THREAD

**Issue by Ribero** [jellyfin/jellyfin-plugin-webhook#20]
I was using Prowl for notification and it was easy and very effective, but it is now deprecated.

I have no idea if I can still use Prowl with this plugin (using generic and template ?).

I also tried pushover (created a test account there, installed the iOS application, made a test from their website : ok) but the lack of explanation on how to configure it on Jellyfin Server and on ant additional steps on pushover makes the whole process completely obscure for basic end-user (yes I am 😄 ).

Any clue on how to configure the plugin to work with prowl or pushover ?

**Comment by crobibero** [comment]
We have a template for Pushover [here](https://github.com/crobibero/jellyfin-plugin-webhook/blob/master/Jellyfin.Plugin.Webhook/Templates/Pushover.handlebars)

I haven't tested with Prowl to see what format it accepts yet

**Comment by crobibero** [comment]
Looks like Prowl only accepts query string parameters, so it will have to be a custom destination. I don't know when I'll get around to adding this
