### ISSUE TITLE
Not working with Kodi Plugin

### ISSUE THREAD

**Issue by Sian-Lee-SA** [jellyfin/jellyfin-plugin-webhook#203]
Using Kodi Jellyfin plugin with playback as Native Mode doesn't cooperate with this plugin. The activity log will be stuck on the first played item then anything played or stopped after would always show "Finished { First Show Name }". The notifications also produces the same even with a simple template string eg. {"test":"test1"} . When removing the plugin or no hook added then the activity log works normally.

Also playing from browser seems ok

**Comment by crobibero** [comment]
There is nothing we can do in the plugin to fix this, sorry. It would be up to the client to report playback correctly.

**Comment by Sian-Lee-SA** [comment]
Strange because their status displays correectly on Jellyfin and relays fine to Home Assistant

**Comment by Sian-Lee-SA** [comment]
And there is techincally something you can do, you can check the data and ensure it's valid else discard fields that aren't
