### ISSUE TITLE
'ItemId' gives id with dashes

### ISSUE THREAD

**Issue by jahlib** [jellyfin/jellyfin-plugin-webhook#204]
I have a webhook template for sending photos to Telegram using the sendPhoto method. The ItemId parameter provides an ID in the following format: 6213b704-a0d9-5429-3110-f4d561b0f614. However, when I use this ID, I receive a "Bad Request" error with the message "wrong file identifier/HTTP URL specified."

To troubleshoot, I tested the API call using curl with the same parameters as in my template. Interestingly, when I remove the dashes from the ItemId, the "Bad Request" error no longer occurs.

This works -
`curl -X POST -H "Content-Type: application/json" -d '{"chat_id":"-XXXXXXXXX","photo":"https://server.domain/Items/6213b704a0d954293110f4d561b0f614/Images/Primary","caption":"sas","disable_notification":"true"}' https://api.telegram.org/botXXXXXXXX:XXXXXXXXXX`

This does Bad Request: wrong file identifier/HTTP URL specified
`curl -X POST -H "Content-Type: application/json" -d '{"chat_id":"-XXXXXXXXX","photo":"https://server.domain/Items/6213b704-a0d9-5429-3110-f4d561b0f614/Images/Primary","caption":"sas","disable_notification":"true"}' https://api.telegram.org/botXXXXXXXX:XXXXXXXXXX`

**Comment by jahlib** [comment]
I have found a solution - {{replace ItemId "-" ""}}

**Comment by jahlib** [comment]
Please add a "replace" helper to Handlebars or include {{ShortItemId}} without dashes.

**Comment by jlcs-es** [comment]
Another solution would be to include https://github.com/Handlebars-Net/Handlebars.Net.Helpers so we can enrich templates without asking for specific helpers each time.

**Comment by Salva-G** [comment]
Any workaround meanwhile?

**Comment by jlcs-es** [comment]
@Salva-G nope, I ended up including the IMDB URL and Telegram includes the preview in the message, but it's just not the same.

**Comment by Salva-G** [comment]
@jlcs-es Can you post a template of the webhook that uses the imdb url? Thanks!

**Comment by jlcs-es** [comment]
@Salva-G you have more examples in the repo, for example the discord templates include more info. My template for Telegram is:

```
{
    "chat_id":"-your id",
    {{#if_equals ItemType 'Season'}}
    "text": "<b>{{ItemType}} Now Available</b>\n\n<b>{{{SeriesName}}} ({{Year}})</b>\n<b><em>{{{Name}}}</em></b>\n{{Overview}}\n\n<b>Runtime</b>\n{{RunTime}}\n\n<b>Status</b>\nAvailable"
    {{else}}
    {{#if_equals ItemType 'Episode'}}
    "text": "<b>Episode Now Available</b>\n\n<b>{{{SeriesName}}} ({{Year}})</b>\n<b>S{{SeasonNumber00}}E{{EpisodeNumber00}}</b> - <b><em>{{{Name}}}</em></b>\n{{Overview}}\n\n<b>Runtime</b>\n{{RunTime}}\n\n<b>Status</b>\nAvailable"
    {{else}}
    "text": "<b>{{ItemType}} Now Available</b>\n\n<b>{{{Name}}} ({{Year}})</b>\n{{Overview}}\n\n<b>Runtime</b>\n{{RunTime}}\n\n<b>Status</b>\nAvailable"
    {{/if_equals}}
    {{/if_equals}},
    "parse_mode": "html",
    "disable_notification":true,
    "link_preview_options": {
        "is_disabled": false,
        {{~#if_exist Provider_imdb~}}"url": "https://www.imdb.com/title/{{Provider_imdb}}/",{{~/if_exist~}}
        "prefer_large_media": true,
        "show_above_text": true
    }
}
```

**Comment by crobibero** [comment]
I can't reproduce the issue where Jellyfin responds with 400 after just changing the Guid without dashes to a Guid with dashes.

**Comment by jlcs-es** [comment]
I just tested and maybe the Jellyfin project updated the behaviour of the URLs to accept both dashed and non-dashed IDs. Would be nice to find the commit/PR of their fix and link it here to close with reason.

**Comment by Salva-G** [comment]
@crobibero Jellyfin accepts dashed and non-dashed guid, but the problem is when at the template you use the item ID variable. It always gives you the one with dashes and when you use it to send the telegram message, telegram rejected it.

**Comment by crobibero** [comment]
> I just tested and maybe the Jellyfin project updated the behaviour of the URLs to accept both dashed and non-dashed IDs. Would be nice to find the commit/PR of their fix and link it here to close with reason.

https://github.com/jellyfin/jellyfin/pull/4749



> @crobibero Jellyfin accepts dashed and non-dashed guid, but the problem is when at the template you use the item ID variable. It always gives you the one with dashes and when you use it to send the telegram message, telegram rejected it.

That is unfortunate, but sadly not something I will be fixing as we are actively moving away from improper Guid formatting.

**Comment by its-wizza** [comment]
> That is unfortunate, but sadly not something I will be fixing as we are actively moving away from improper Guid formatting.

Is this still the case?

By default, the Jellyfin API still seems to be receiving/returning Guid values without hyphens:

`GET https://jellyfin.server/users`

```
[{
        "Name": "mytv",
        "ServerId": "d87e91c4c07a2c8da2c43ca1140f080c",
        "Id": "3c61688701ed476f9a3a198d567f414b",
        "HasPassword": true,
        "HasConfiguredPassword": true,
        "HasConfiguredEasyPassword": false,
        "EnableAutoLogin": false,
        "Configuration": {
...
```

`GET https://jellyfin.server/Users/3c61688701ed476f9a3a198d567f414b`

```
{
    "Name": "mytv",
    "ServerId": "d87e91c4c07a2c8da2c43ca1140f080c",
    "Id": "3c61688701ed476f9a3a198d567f414b",
    "HasPassword": true,
    "HasConfiguredPassword": true,
    "HasConfiguredEasyPassword": false,
    "EnableAutoLogin": false,
    "LastLoginDate": "2026-01-26T07:21:03.5084251Z",
    "LastActivityDate": "2026-01-26T11:55:16.4709609Z",
    "Configuration": {
...
```

I think, given this, the Guid without hyphens should be made available via the Webhook plugin.

Other services such as Seerr replicate the Jellyfin method of no dashes in Guid. Therefore the Webhook plugin is unable to interact with the Seerr API.
