### ISSUE TITLE
Plugin returns Malfunctioned status

### ISSUE THREAD

**Issue by fattykidd** [jellyfin/jellyfin-plugin-webhook#209]
I've been trying to install this plugin for a few days now, It repeatedly returns a "Malfunctioned Status".
Server Info: Official latest Jellyfin image for docker.
Server: Fatty's Jellyfin
Version: 10.8.13
Operating System: Linux
Architecture: X64
Log attached starting from server restart 

[jellyfin.log](https://github.com/jellyfin/jellyfin-plugin-webhook/files/13798786/jellyfin.log)

**Comment by crobibero** [comment]
Remove the SMTP notifications plugin

**Comment by fattykidd** [comment]
> Remove the SMTP notifications plugin

And fixed..
