### ISSUE TITLE
Sending photos (memories) by date to the mail.

### ISSUE THREAD

**Issue by VlaK0r** [jellyfin/jellyfin-plugin-webhook#213]
Hi!
Thank you for your hard work.

Is it possible to use the plugin "Webhook" to send photos to the mail depending on the date? Something similar to memories from Google photos.

**Comment by crobibero** [comment]
I'm not completely sure what you're looking to do but Jellyfin isn't really meant for photos- so I'm going to say no and recommend using something like Immich.

**Comment by VlaK0r** [comment]
> I'm not completely sure what you're looking to do but Jellyfin isn't really meant for photos- so I'm going to say no and recommend using something like Immich.

![изображение](https://github.com/jellyfin/jellyfin-plugin-webhook/assets/77666575/f9236da7-1bff-40ca-ad7d-bee2f13176e2)

Why is it not intended? The opposite is written on the main page of the project.
