### ISSUE TITLE
not sending all webhooks

### ISSUE THREAD

**Issue by reitenth** [jellyfin/jellyfin-plugin-webhook#222]
its only sending session_start even in log in and out.
https://gist.github.com/reitenth/9f02002513bf7d00037489086cdf6714

**Comment by crobibero** [comment]
No information provided.

**Comment by reitenth** [comment]
idk what information you need lol. i gave u wat i thought were relevant logs.
here is notifiarr only sending session_start notifications despite every webhook being enabled.
![image](https://github.com/jellyfin/jellyfin-plugin-webhook/assets/94771708/d8c52167-0fea-410f-83e8-a5b8f91e02d4)
![image](https://github.com/jellyfin/jellyfin-plugin-webhook/assets/94771708/6b1a8eb9-e072-4277-ae4b-0de8d85580ab)
