### ISSUE TITLE
Can't get Discord notifications for Authentication Success/Fails to work

### ISSUE THREAD

**Issue by HouseIndoril** [jellyfin/jellyfin-plugin-webhook#224]
I initially tacked on my $0.02 to [#177](https://github.com/jellyfin/jellyfin-plugin-webhook/issues/177), which was then closed in reference to [this](https://github.com/jellyfin/jellyfin/pull/8960) from January of 2023. Given we have multiple individuals reporting it doesn't work as recently as yesterday, there might need to be some updated documentation posted/other attention if this feature is expected to be working on the most recent branches of Jellyfin and the Webhook Plugin. 

I have 2 existing notifications working for playback stop/start. Those worked perfect from the start, no extra messing with `logging.json` was required to get those to work, but I did modify my `logging.json` file according to the [instructions](https://github.com/jellyfin/jellyfin-plugin-webhook#my-webhook-isnt-working) to no effect. 

Not really sure where to start with this one. I'm not terribly proficient with the templates so if there's a more fleshed out template I can use, that'd be great. 

Here's my logging.json file. 
```{
    "Serilog": {
        "MinimumLevel": {
            "Default": "Information",
            "Override": {
                "Microsoft": "Warning",
                "System": "Warning",
                "Jellyfin.Plugin.Webhook": "Debug"
            }
        },
        "WriteTo": [
            {
                "Name": "Console",
                "Args": {
                    "outputTemplate": "[{Timestamp:HH:mm:ss}] [{Level:u3}] {Message:lj}{NewLine}{Exception}"
                }
            },
            {
                "Name": "Async",
                "Args": {
                    "configure": [
                        {
                            "Name": "File",
                            "Args": {
                                "path": "%JELLYFIN_LOG_DIR%//jellyfin.log",
                                "fileSizeLimitBytes": 10485700,
                                "rollOnFileSizeLimit": true,
                                "retainedFileCountLimit": 10,
                                "outputTemplate": "[{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz}] [{Level:u3}] {Message}{NewLine}{Exception}"
                            }
                        }
                    ]
                }
            }
        ]
    }
}
```

I can see failed login attempts in the jellyfin application logs but it seems the plugin is simply unaware of them. 
```
[2024-04-07 11:49:33.934 -04:00] [ERR] Error authenticating with provider "Default"
MediaBrowser.Controller.Authentication.AuthenticationException: Specified user does not exist.
   at Jellyfin.Server.Implementations.Users.DefaultAuthenticationProvider.Authenticate(String username, String password, User resolvedUser)
   at Jellyfin.Server.Implementations.Users.UserManager.AuthenticateWithProvider(IAuthenticationProvider provider, String username, String password, User resolvedUser)
[2024-04-07 11:49:33.937 -04:00] [INF] Authentication request for "lalalala" has been denied (IP: "192.168.2.3").
[2024-04-07 11:49:33.938 -04:00] [ERR] Error processing request: "Invalid username or password entered". URL "POST" "/Users/authenticatebyname"
```

**Comment by crobibero** [comment]
This is a duplicate issue. The fix is in 10.9, not 10.8.
