### ISSUE TITLE
[Bug] Double Notifications when using Jellyfin Media Player App on Mac or iPhone

### ISSUE THREAD

**Issue by lukaslindnermusic** [jellyfin/jellyfin-plugin-webhook#229]
Hey there,

I have set up webhook notifications for the Session Started Event for Discord as well as ntfy.

When I open a new session in the browser, I get one notification how it should be.
However, if I open either the iPhone app or the macos app, I get the notification twice.

I don't know if this is an issue from the plugin or jellyfin itself. 
Does anyone know how to fix this? 

Limiting the webhook to a single user does not change this behavior.

Discord Hook:
{
    "content": "{{MentionType}}",
    "avatar_url": "{{AvatarUrl}}",
    "username": "{{BotUsername}}",
    "embeds": [
        {
            "color": "{{EmbedColor}}",
            "footer": {
                "text": "From {{{ServerName}}}",
                "icon_url": "{{AvatarUrl}}"
            },
            "title": "{{{NotificationUsername}}} - Session Started"
        }
    ]
}

ntfy hook:
{
    "topic": "jellyfin",
    "tags": ["popcorn"],
    "title": "{{{NotificationUsername}}} - Session Started",
    "priority": 1,
    "message": "{{{NotificationUsername}}} started a Session on {{{ServerName}}}"
}

webhook 11.0.0.0
jellyfin in docker on Synology DS920+
Version: 10.8.13
Operating System: Linux
Architecture: X64

**Comment by crobibero** [comment]
That would be an issue within the client. The plugin just forwards events that the server receives.

**Comment by lukaslindnermusic** [comment]
Just an update on this:
With the new Jellyfin Server Versions, the bug is gone and the event is only triggered once 👍
