### ISSUE TITLE
Generic notification "ItemAdded" doesnt work

### ISSUE THREAD

**Issue by naxeras** [jellyfin/jellyfin-plugin-webhook#232]
Hi,

I updated my Jellyfin Server to 10.9 and now 10.9.1. Since then, the webhook Generic notification "ItemAdded" no longer work for me.

I enabled debug log but nothing is showed except this: ¿It is possible a issue by jellyfin?

>[2024-05-13 12:25:27.066 +02:00] [DBG] [58] Jellyfin.Plugin.Webhook.Notifiers.ItemAddedNotifier.ItemAddedManager: ProcessItemsAsync

If I add "Playback Start" to the "Notification Type" and the message works. So it's not the plugin or its setting. It doesn't seem to see that something new has been added.

In the jellyfin official forums another people have the exact same issue:

https://forum.jellyfin.org/t-webhooks-no-longer-work-since-update-to-10-9

Any help?

Regards.

**Comment by talesam** [comment]
The same thing happened to me, I tested everything, now I saw that the problem was not with my bot, but a bug in the webhooks.

**Comment by lukaslindnermusic** [comment]
Sadly, the problem seems to be back. 
The same template successfully sends ntfy notifications for "Playback Started", but not for "ItemAdded".
```
{
	"topic": "jellyfin-news",
	"priority": 3,
	{{#if_equals NotificationUsername 'Lukas'}}
		"click": "https://jellyfin.domain.com/web/#/details?id={{ItemId}}",
	{{else}}
		"click": "https://jellyfin.vpn.domain.com/web/#/details?id={{ItemId}}",
	{{/if_equals}}
	{{#if_equals ItemType 'Episode'}}
		"tags": ["tv"],
		"title": "New Episode added",
		"message": "{{{SeriesName}}}\nS{{SeasonNumber00}}E{{EpisodeNumber00}} - {{{Name}}} is now available on Jellyfin."
	{{else}}
		{{#if_equals ItemType 'Audio'}}
			"tags": ["headphones"],
			"title": "New Track added",
			{{~#if_exist Year~}}
				"message": "{{{Name}}} ({{Year}}) is now available on Jellyfin."
			{{else}}
				"message": "{{{Name}}} is now available on Jellyfin."
			{{~/if_exist~}}
		{{else}}
			"tags": ["popcorn"],
			"title": "New Film added",
			{{~#if_exist Year~}}
				"message": "{{{Name}}} ({{Year}}) is now available on Jellyfin."
			{{else}}
				"message": "{{{Name}}} is now available on Jellyfin."
			{{~/if_exist~}}
		{{/if_equals}}
	{{/if_equals}}
}
``` 

Jellyfin Version: 10.10.7
Webhook Plugin Version: 17.0.0.0


Thanks for any help!
