### ISSUE TITLE
Plugin incompatible with Jellyfin 10.9.x

### ISSUE THREAD

**Issue by GeiserX** [jellyfin/jellyfin-plugin-webhook#235]
Check forum post: https://forum.jellyfin.org/t-webhooks-no-longer-work-since-update-to-10-9

**Comment by crobibero** [comment]
Duplicate of https://github.com/jellyfin/jellyfin-plugin-webhook/issues/232

**Comment by GeiserX** [comment]
Great! Thank you. But would you create a new Release so that we can have the functionality back?

**Comment by crobibero** [comment]
Release isn't ready yet, there is another issue to fix before it is.
