### ISSUE TITLE
This really needs some examples/tutorials

### ISSUE THREAD

**Issue by michael-zock** [jellyfin/jellyfin-plugin-webhook#241]
Gave it a try, since 10.9 wants this as its new main notification plugin and after 10 minutes of it not working with Pushbullet I nuked it off my system again.

**Comment by crobibero** [comment]
Ok

**Comment by michael-zock** [comment]
@crobibero Thanks for at least making it public that you don't give a shit about usability.

**Comment by mad-tunes** [comment]
I'm at least the second person who's found this really tricky to use (in https://github.com/jellyfin/jellyfin-plugin-webhook/issues/267)
I'm not trying to do anything elaborate, but have spent aaages and really struggled to brute-force anything that's useful.
