### ISSUE TITLE
Build doesn't work

### ISSUE THREAD

**Issue by Playragnarok** [jellyfin/jellyfin-plugin-webhook#254]
I tried to build my config and get .dll
When i put it on plugin folder
Status Non-supported and waring plugin not setting

**Comment by crobibero** [comment]
This isn't really enough information to attempt to help out with. 

To start- what version of Jellyfin are you running? What do the logs say as to why the plugin is failing to load? What did you change to need to require building the plugin?

**Comment by Playragnarok** [comment]
> This isn't really enough information to attempt to help out with.
> 
> To start- what version of Jellyfin are you running? What do the logs say as to why the plugin is failing to load? What did you change to need to require building the plugin?

Running on Jellyfin version 10.9.3
Logs - nothing report
I gonna to add delay send notifications just second

**Comment by crobibero** [comment]
You likely need to edit meta.json to remove the unsupported flag, and then check the logs again. Jellyfin will report the reason the load failed

**Comment by Playragnarok** [comment]
`[2024-06-02 19:43:19.577 +07:00] [ERR] [1] Emby.Server.Implementations.Plugins.PluginManager: Failed to load assembly "C:\ProgramData\Jellyfin\Server\plugins\Webhookss_14.0.0.0\Jellyfin.Plugin.Webhook.dll". This error occurs when a plugin references an incompatible version of one of the shared libraries. Disabling plugin
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'MediaBrowser.Controller, Version=10.9.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'MediaBrowser.Common, Version=10.9.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'MediaBrowser.Controller, Version=10.9.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'MediaBrowser.Controller, Version=10.9.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'MediaBrowser.Controller, Version=10.9.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'MediaBrowser.Controller, Version=10.9.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'MediaBrowser.Controller, Version=10.9.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'MediaBrowser.Controller, Version=10.9.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'MediaBrowser.Controller, Version=10.9.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'MediaBrowser.Controller, Version=10.9.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'MediaBrowser.Controller, Version=10.9.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'MediaBrowser.Controller, Version=10.9.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'MediaBrowser.Controller, Version=10.9.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'MediaBrowser.Controller, Version=10.9.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'MediaBrowser.Controller, Version=10.9.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'MediaBrowser.Controller, Version=10.9.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'MediaBrowser.Controller, Version=10.9.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'MediaBrowser.Controller, Version=10.9.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'MediaBrowser.Controller, Version=10.9.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'MediaBrowser.Controller, Version=10.9.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'MediaBrowser.Controller, Version=10.9.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'MediaBrowser.Controller, Version=10.9.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'MediaBrowser.Model, Version=10.9.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'MQTTnet, Version=4.3.6.1152, Culture=neutral, PublicKeyToken=fdb7629f2e364a63'. The system cannot find the file specified.
Could not load file or assembly 'MQTTnet, Version=4.3.6.1152, Culture=neutral, PublicKeyToken=fdb7629f2e364a63'. The system cannot find the file specified.
Could not load file or assembly 'MediaBrowser.Model, Version=10.9.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'MediaBrowser.Model, Version=10.9.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'Jellyfin.Data, Version=10.9.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'Jellyfin.Data, Version=10.9.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'Jellyfin.Data, Version=10.9.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.`
meta.json edit  to "targetAbi": "10.9.3.0",  rather assembly location not found

**Comment by Playragnarok** [comment]
before edit
```
[2024-06-02 22:01:29.880 +07:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Skipping disabled plugin "14.0.0.0" of "Webhook" 
[2024-06-02 22:01:30.516 +07:00] [ERR] [1] Emby.Server.Implementations.Plugins.PluginManager: Failed to load assembly "C:\ProgramData\Jellyfin\Server\plugins\Webhoosk_14.0.0.0\Jellyfin.Plugin.Webhook.dll". This error occurs when a plugin references an incompatible version of one of the shared libraries. Disabling plugin
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'MediaBrowser.Controller, Version=10.9.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'MediaBrowser.Common, Version=10.9.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'MediaBrowser.Controller, Version=10.9.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'MediaBrowser.Model, Version=10.9.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'MQTTnet, Version=4.3.6.1152, Culture=neutral, PublicKeyToken=fdb7629f2e364a63'. The system cannot find the file specified.
Could not load file or assembly 'MQTTnet, Version=4.3.6.1152, Culture=neutral, PublicKeyToken=fdb7629f2e364a63'. The system cannot find the file specified.
Could not load file or assembly 'MediaBrowser.Model, Version=10.9.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'MediaBrowser.Model, Version=10.9.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'Jellyfin.Data, Version=10.9.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
```

after edit meta.json is "targetAbi": "10.9.1.0", to "10.9.4.0",
`Emby.Server.Implementations.Plugins.PluginManager: Skipping disabled plugin "14.0.0.0" of "Webhook" `

**Comment by crobibero** [comment]
https://github.com/jellyfin/jellyfin-plugin-webhook/blob/be96b6261f4c36aa7711e53eb0a2a490aca8ebab/Jellyfin.Plugin.Webhook/Jellyfin.Plugin.Webhook.csproj#L14

This line says to load the most up-to-date version of the library, so you're building against 10.9.4 and then trying to run using 10.9.1.

Either specify the package version explicitly or upgrade your Jellyfin server.

**Comment by Playragnarok** [comment]
Sovled
