### ISSUE TITLE
Getting nowhere setting up a simple notification, help!

### ISSUE THREAD

**Issue by mad-tunes** [jellyfin/jellyfin-plugin-webhook#267]
I've not long realised notifications through the Email Notifications plugin had stopped, and that it's been replaced.

I'm trying to replicate the basic emails I used to be sent so I knew when Jellyfin was in use by someone else, but I just can't get it to send me a pretty simple email like:

%user% started/stopped playing %media title%

How can this be done now please?

**Comment by crobibero** [comment]
I'm currently unable to test but something like the following in the template textarea should work

`{{NotificationUsername}} started/stopped playing {{Name}}`

**Comment by mad-tunes** [comment]
Thanks.

I was hoping to include either started or stopped though, not both.
I should probabbly have elaborated a little more.

Play a movie: James started/stopped playing Alien: Romulus (can it be started when started and stopped when it was stopped?)
Stop playing a movie: James started/stopped playing Alien: Romulus (can it be started when started and stopped when it was stopped?)
Start playing TV: James started/stopped playing The Unwanted Personification of Terry (can it be TV series name?)
Stop playing TV: James started/stopped playing The Unwanted Personification of Terry (can it be TV series name?
Start playing music: James started/stopped playing i like the way you kiss me (I started playing an album, but it emails twice about every single track. Can it be album?)
Stop playing music: James started/stopped playing i like the way you kiss me (I stopped playing an album, but it emails twice about every single track. Can it be album?)

To replicate the previously really simple to enable notifications, it looks like it'd need a bunch of IFs (that, even chopping bits out of examples, I haven't been able to get working), and/or fields that don't seem to be available (or at least aren't listed anywhere I can find)...

How can IFs be done?
How could TV Series and music artist/album be included?

Thanks

**Comment by mad-tunes** [comment]
That's let me get a lot closers to what I'm after, with:
```
{{~#if_equals NotificationType 'PlaybackStart'~}}
	{{~#if_equals ItemType 'Episode'~}}
		{{NotificationUsername}} started playing TV {{SeriesName}}
	{{/if_equals}}
	{{~#if_equals ItemType 'Movie'~}}
		{{NotificationUsername}} started playing movie {{Name}}
	{{/if_equals}}
	{{~#if_equals ItemType 'Audio'~}}
		{{NotificationUsername}} started playing music {{Name}}
	{{/if_equals}}
{{/if_equals}}

{{~#if_equals NotificationType 'PlaybackStop'~}}
	{{~#if_equals ItemType 'Episode'~}}
		{{NotificationUsername}} stopped playing TV {{SeriesName}}
	{{/if_equals}}
	{{~#if_equals ItemType 'Movie'~}}
		{{NotificationUsername}} stopped playing movie {{Name}}
	{{/if_equals}}
	{{~#if_equals ItemType 'Audio'~}}
		{{NotificationUsername}} stopped playing music {{Name}}
	{{/if_equals}}
{{/if_equals}}

```
...thanks a lot.
but, while it's easy to get the series name instead of episode name using SeriesName, is there similar for music? So I could list the album thats being played rather than the individual track?

**Comment by crobibero** [comment]
Should be under `{{Album}}` instead of `{{Name}}`

https://github.com/jellyfin/jellyfin-plugin-webhook/blob/master/Jellyfin.Plugin.Webhook/Helpers/DataObjectHelpers.cs#L163-L180

**Comment by mad-tunes** [comment]
That wasn't the last thing... links, how can I change the text that's displayed for them please?

Is there some documentation that I'm missing? If I could find how to do these things without asking, I honestly would be..

**Comment by mad-tunes** [comment]
I cant figure out how to build a simple subject line either.

Something like `Jellyfin:  {{NotificationUsername}} stopped playing TV` produces 'Jellyfin:James stopped playing TV'
How can I keep the space after the :, so it's properly readable?
