### ISSUE TITLE
SMTP notification for "SessionStart" sends two emails

### ISSUE THREAD

**Issue by nylimited** [jellyfin/jellyfin-plugin-webhook#269]
Using email notifications via SMTP generally works fine except for the "SessionStart" notification. This one triggers 2 emails, perhaps a second or less apart.. The Jellyfin logs show only a single trigger but the double emails are consistent regardless of the connection source and software used to connect.

```
[2024-08-27 12:27:30.180 -04:00] [INF] [37] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "::ffff:192.168.1.166" closed
[2024-08-27 12:27:41.859 -04:00] [INF] [108] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "::ffff:192.168.1.166" request
```

The above lines are the only entries shown/added to the JF log at the time of a user connecting. 

I would think that it should be relatively simple to suppress identical double notifications (triggered with X seconds of each other) even if the start of a session is doubled up for some reason within JF itself.

**Comment by chiragkrishna** [comment]
Same on telegram and gotify also, double notifications are present. Came to report it and saw your post.
