### ISSUE TITLE
Pushover isn't honoring device?

### ISSUE THREAD

**Issue by pyrodex** [jellyfin/jellyfin-plugin-webhook#291]
I have pushover setup and want to ONLY send these to a single device but have multiple devices in my pushover settings. I have the device define as a single name (phoneX) but JellyFin isn't honoring this and sending it to all devices with pushover installed. I even went as far as removing the pushover configuration, restarted jellyfin, and re-added, then restarted one more time but it is still using ALL devices. How do I fix this?

**Comment by crobibero** [comment]
Please provide the template you are using.

**Comment by pyrodex** [comment]
> Please provide the template you are using.

I am using the latest file, untouched from https://github.com/jellyfin/jellyfin-plugin-webhook/blob/master/Jellyfin.Plugin.Webhook/Templates/Pushover/AllInOne.handlebars.

**Comment by crobibero** [comment]
That template doesn't specify which device to use, you would need to add `"device": "your-device-name-here"` to the template.
