### ISSUE TITLE
Need little help :d !!

### ISSUE THREAD

**Issue by moarf56** [jellyfin/jellyfin-plugin-webhook#30]
Hello,

I just installed the webhook plugin and would like a little help setting it up.
I am using Gotify so:

Server Url: the URL of my gotify server like "http://xxx.xxx.xxx.xxx:xx"

Next add Gotify then : 
Webhook Name: the name I want
Webhook Url: ???
Notification Type: select what I want
 Template: I take the exemple
 Token: ok
Priority : 0

Thx :d

**Comment by crobibero** [comment]
I’m not sure what you’re asking, can you please clarify what your question/issue is?

**Comment by moarf56** [comment]
Yes of course !!
What I have to put on "Webhook Url"  field ? I try the adress of my gotify server "http://xxx.xxx.xxx.xxx:xx" or "http://xxx.xxx.xxx.xxx:xx/message".

With this I have no positive result.

Thx.

**Comment by crobibero** [comment]
Sorry for the delayed response.

You enter `http://gotify.domain.tld`, the `/message` is automatically appended. If you're not having success, please provide logs so we can be of better assistance.

**Comment by moarf56** [comment]
> 
> 
> Sorry for the delayed response.
> 
> You enter `http://gotify.domain.tld`, the `/message` is automatically appended. If you're not having success, please provide logs so we can be of better assistance.



Hey !! No probelm ! Thx for your help all work fine now !
