### ISSUE TITLE
Item Type checkbox unsync with plugin configuration

### ISSUE THREAD

**Issue by smallghost** [jellyfin/jellyfin-plugin-webhook#45]
When i uncheck some `Item Type` in plugin setting page, i saw the plugin configuration xml content is correct, but in jellyfin plugin setting UI, all item types always checked, it is hard to know what item types i need to handle.

**Comment by crobibero** [comment]
Which ItemType aren’t being updated in the webui?

**Comment by smallghost** [comment]
every types
