### ISSUE TITLE
How to configure this plugin?

### ISSUE THREAD

**Issue by wsw70** [jellyfin/jellyfin-plugin-webhook#47]
I apologize if the question is obvious, but I do not understand how this plugin is supposed to be configured.

I installed it - when clicking on the plugin in Jellyfin it states that there is nothing to configure.

From the server perspective, I see a `plugin` directory, and in there, there is a directory for `Webhook`. I guess that a template file (as found in https://github.com/jellyfin/jellyfin-plugin-webhook/tree/master/Jellyfin.Plugin.Webhook/Templates) is the way to configure the plugin

- where should it be placed?
- is it recognized as a config file because of its extension?

**Comment by crobibero** [comment]
Did you restart Jellyfin after installing the plugin? There’s a pretty extensive configuration page

**Comment by wsw70** [comment]
@crobibero ah yes, thank you! Restarting indeed brought in the configuration panel.
