### ISSUE TITLE
{{{Username}}} for Discord returns bot name instead of Jellyfin user

### ISSUE THREAD

**Issue by nearcatch** [jellyfin/jellyfin-plugin-webhook#56]
Trying to do something like this
```
"title": "{{{Username}}} is playing {{{SeriesName}}} S{{SeasonNumber00}}E{{EpisodeNumber00}}: {{{Name}}}",
```
But it's returning the "Webhook Username" instead of the Jellyfin user. According to the readme "Username" should map to the Jellyfin user for Playback items. For Discord that doesn't work, since "Username" is used for the Webhook Username.

I would suggest changing the Webhook Username variable to be "WebhookUsername" instead of Username.

**Comment by nearcatch** [comment]
This is the fastest I've ever had a bug worked on, wow!

But it doesn't seem to work, was testing with below line:
```
"title": "{{{NotificationUsername}}} is playing {{{Name}}} ({{Year}})",
```
Results in this:
![image](https://user-images.githubusercontent.com/692914/133174106-0f8f0112-55b5-481b-b82b-b372ac4ec912.png)

I looked at the pull request and the file DataObjectHelpers.cs seems odd to me. Some lines have `dataObject["NotificationUsername"] = user.Name.Escape();` and others have `dataObject["NotificationUsername"] = user.Username.Escape();`. Maybe that's an issue?

**Comment by crobibero** [comment]
Looks like I missed some properties, can you try the plugin attached to this PR? 
https://github.com/jellyfin/jellyfin-plugin-webhook/pull/58

**Comment by nearcatch** [comment]
Tried it out and it's returning the usernames correctly now, thanks.
