### ISSUE TITLE
Feature request/modification: Provide variable for UserId without dashes

### ISSUE THREAD

**Issue by nearcatch** [jellyfin/jellyfin-plugin-webhook#63]
Trying to use this in a discord embed:
```json
"author": {
  "name": "{{{NotificationUsername}}}",
  "icon_url": "{{ServerUrl}}/Users/{{{UserId}}}/Images/Primary"
},
```

But {{UserId}} provides `05c25ff3-c938-c8fa-d910-610675d9d9f9`. Jellyfin's link to the image does not use dashes: `05c25ff3c938c8fad910610675d9d9f9`. The image link becomes invalid when using the plugin's {{UserId}} variable.

**Comment by nearcatch** [comment]
Never mind I guess? The url was previously not working but now it does. Not sure what was going on.

**Comment by crobibero** [comment]
Just to clarify- Jellyfin parses the guid string to a proper guid. We send it out without dashes to not break legacy. clients

**Comment by nearcatch** [comment]
Yeah I could see that, but the author icon wasn't working properly and when I viewed the profile image directly in Jellyfin the path didn't include the dashes, so I was confused and thought that the discord embed wasn't building the link properly. But later when I viewed the profile image in Jellyfin again it had dashes. Not sure what happened, but it's working now.
