### ISSUE TITLE
Issue disabling some Notification Type or User

### ISSUE THREAD

**Issue by nodje** [jellyfin/jellyfin-plugin-webhook#87]
I'm using SMTP and Gotify Destination, and I get a flood of notification for playback progress, even though this Notification Type is disabled for both Destination.
Worse, USer filter for SMTP Destination has no user checked but still sends lots of notification.

Not sure what to provide here to help reproduce.

**Comment by crobibero** [comment]
> I'm using SMTP and Gotify Destination, and I get a flood of notification for playback progress, even though this Notification Type is disabled for both Destination.

I don't see how that's possible. Can you please provide more information, such as logs or your config file.

>  Worse, USer filter for SMTP Destination has no user checked but still sends lots of notification.

If no filter is selected, no filter will be applied.

**Comment by nodje** [comment]
OK, I was tricked by the `User Data Saved' which keep firing, and I didn't have the type of notification in the alert.

> If no filter is selected, no filter will be applied.
I'm not sure what you mean by that: to my understanding, if no user is checked, no one should receive notifications.

**Comment by nodje** [comment]
ok, I get it know, sorry for the confusion.

It's a filter for event coming FROM selected user, and not to send TO a selection of users.

Originally I installed the Webhook plugin to be able to alert a selection of users of new content being added.

In the end, going to Admin Dashboard/s Notification, I still can't find a way to achieve this.
I can select to which users I want to send the specific `New content added` notification, but selecting the `Use the following services` I can only select `Webhook: Generic Notifier`, which doesn't let me specify a Per User notification service.

So I have a Per User filter at the Jellyfin Notification level, but I have no way to specify a notification preference at the user level.

Am I right, or is there something possible to achieve per user alerting using Webhook?

**Comment by crobibero** [comment]
Sounds like you want this feature request
https://github.com/jellyfin/jellyfin-plugin-webhook/issues/74

**Comment by nodje** [comment]
Thanks, sounds about right.

But I think there should be an additional layer of abstraction provided by Jellyfin, where each User is allowed to choose and configure among a set of communication channel (basically let user provide email go start with)

Webhook definitely sounds for admin only notification to me, and could be used to "force" push notification on specific channel to user, according to some condition. Could be quota of some sorts or the like.
