### ISSUE TITLE
Crobibero's Repo Throwing Errors

### ISSUE THREAD

**Issue by gfxlight55** [jellyfin/jellyfin-plugin-webhook#97]
Didn't know where to put this as the Repo maintainer doesn't seem to have a way to report this issue.

Jellyfin Console Log:

[ERR] [42] Emby.Server.Implementations.Updates.InstallationManager: An error occurred while accessing the plugin manifest: https://repo.codyrobibero.dev/manifest.json
System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.Json.HttpClientJsonExtensions.GetFromJsonAsyncCore[T](Task`1 taskResponse, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.GetPackages(String manifestName, String manifest, Boolean filterIncompatible, CancellationToken cancellationToken)

Website Error:

Error 1034
Ray ID: 6d25d78a89b75790 • 2022-01-24 02:30:48 UTC
Edge IP Restricted
What happened?
You've requested a page on a website that is part of the Cloudflare network. The host (repo.codyrobibero.dev) resolved to an IP address that the owner of the website does not have access to.

What can I do?
If you are a visitor of this website:
Please try again in a few minutes.

If you are the owner of this website:
Check your DNS records to ensure they are pointed to the IP address(es) you were assigned at registration.

Cloudflare Ray ID: 6d25d78a89b75790 • Your IP: 172.241.xxx.xxx • Performance & security by Cloudflare

**Comment by crobibero** [comment]
Thank you for letting me know, looks like Cloudflare has broken my setup. 

fyi- the webhook plugin has been moved to the Jellyfin organization and my personal repo is no longer required. I _think_ I'll be able to move the rest of the plugins into the org depending if they still work.

I will update here once I figure out a new hosting method.

**Comment by crobibero** [comment]
The plugins are being moved to the Jellyfin repo, so my repo is no longer needed.
